security:
  basic:
    enabled: true
  user:
    name: user123
    password: password
server:
  port: 1111
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user123:password@localhost:${server.port}/eureka/
#  environment: dev
#  atacenter: sinosoft
  instance:
    ip-address: true
#  server:
#    enable-self-preservation:
