server:
  port: 4444
spring:
  application:
    name: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://user123:password@localhost:1111/eureka/
feign:
  hystrix:
    enabled: true